services:
  enshrouded:
    build:
      context: .
      dockerfile: dockerfiles/proton.Dockerfile
    image: mornedhels/enshrouded-server:dev-proton
    container_name: enshrouded
    hostname: enshrouded
    restart: unless-stopped
    stop_grace_period: 90s
    ports:
      - "15637:15637/udp"
    volumes:
      - ./game:/opt/enshrouded
    environment:
      - SERVER_NAME=MornedhelsTest
      - PUID=4711
      - PGID=4711
      - UPDATE_CRON=*/30 * * * *
      - log_level=50
